# Site settings
title: Singapore
client:
  name: Qantas, Changi Airport and Singapore Tourism Board
  link: https://ad.doubleclick.net/ddm/clk/444496833;247723974;z
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Singapore is a playground of colourful adventure. Don’t miss the chance to stopover with Qantas and explore this truly vibrant city state. From a bustling foodie scene that includes forward-thinking Michelin restaurants and coveted hawker stands, to the melting-pot neighbourhoods brimming with culture and the futuristic skyline of Marina Bay, Singapore is a land of diversity, contrasts and compelling exploration. Our Asia editor and Singapore resident Jessica Little gives the lowdown on how to embrace the ‘city of possibilities’ on a four-day stopover.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/qantas-singapore" # the subpath of your site, e.g. /blog/
img:     "/qantas-singapore/_assets/img"
css:     "/qantas-singapore/_assets/css"
js:      "/qantas-singapore/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed